apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: goodbye
spec:
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye World!"        
