apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: hello-task-run
spec:
  taskSpec:
    steps:
      - name: echo
        image: alpine
        script: |
          #!/bin/sh
          echo "Hello World"        

