apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-security-context
spec:
  rules:
  - name: mutate-pipeline
    match:
      any:
      - resources:
          kinds:
          - PipelineRun
    mutate:
      patchStrategicMerge:
        spec:
          podTemplate:
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              runAsNonRoot: true
              runAsUser: 2000
              runAsGroup: 3000
              fsGroup: 2000      
              privileged: false
              capabilities:
                drop: 
                - ALL
              allowPrivilegeEscalation: false
  - name: mutate-task
    match:
      any:
      - resources:
          kinds:
          - Task
    mutate:
      patchStrategicMerge:
        spec:
          steps:
          - (name): "?*"
            securityContext:
              seccompProfile:
                type: RuntimeDefault
              runAsNonRoot: true
              runAsUser: 2000
              runAsGroup: 3000
              fsGroup: 2000      
              privileged: false
              capabilities:
                drop: 
                - ALL
              allowPrivilegeEscalation: false