apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-task-runs
  annotations:
    policies.kyverno.io/title: Block TaskRun
    policies.kyverno.io/category: Tekton
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: TaskRun
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Restrict creation of TaskRun resources to the Tekton pipelines controller.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: check-user
    match:
      any:
      - resources:
          kinds:
            - TaskRun
    exclude:
      any:
      - subjects:
        - kind: User 
          name: "system:serviceaccount:tekton-pipelines:tekton-pipelines-controller"
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    validate:
      message: Creating a TaskRun is not allowed.
      deny: {}