---
apiVersion: v1
kind: Namespace
metadata:
  name: common
---
apiVersion: v1
data:
 cosign.key: LS0tLS1CRUdJTiBFTkNSWVBURUQgQ09TSUdOIFBSSVZBVEUgS0VZLS0tLS0KZXlKclpHWWlPbnNpYm1GdFpTSTZJbk5qY25sd2RDSXNJbkJoY21GdGN5STZleUpPSWpvek1qYzJPQ3dpY2lJNgpPQ3dpY0NJNk1YMHNJbk5oYkhRaU9pSnVVMWxUWVhsclFYWkVPSFZPVG1kR1QzZHRkMFp3TDNsNVpIZDZUMlZoClMwMXNkVFZ4UjJKVU9FSTBQU0o5TENKamFYQm9aWElpT25zaWJtRnRaU0k2SW01aFkyd3ZjMlZqY21WMFltOTQKSWl3aWJtOXVZMlVpT2lKaE9FdDFVV1Z6T0ZvNE1qZ3pZMlZhY0VreGNXZFZMMHc0YWxseFJISk5jaUo5TENKagphWEJvWlhKMFpYaDBJam9pTnpOTVpGbG9TR0ZxUjBGV2FreFpZMGRVZEhWWGJsVXJPRVZYVjFCNFQwWkNSbmxKCmFEQXhXbXBzSzBGalZsWmtlVlJYUldOdFkyaHBaWFJQVW5CTWVGWTFXWGRwTHpKdmNuUnFWa1l6TkRnMFJqaG4KU1VJNGFVdExVa2hvWTJOS1dWVkVhazlCYkRKV1EzbEdObkowTlZoRVMxcFBhemRrUkROd1JHYzRaMWxqVGxWawpielZTUkZGelRHRjFOR3c1TW05U2EyWXpLMGRHYUhGTE5FdHRWMlpoUlRKSE9FRnJSMVJyVDFSRU1XUnhhVXN4ClZYZFlSalZGV0hkU00yOU5ibU13WTNwT1dYTkZXazlrYTFFOVBTSjkKLS0tLS1FTkQgRU5DUllQVEVEIENPU0lHTiBQUklWQVRFIEtFWS0tLS0tCg== 
kind: Secret
metadata:
 name: cosign-private-key
 namespace: common
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-account
  namespace: common
secrets:
- name: img-registry-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  namespace: common
  annotations:
    kubernetes.io/service-account.name: pipeline-account
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
  namespace: common
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: pipeline-account
---
