---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-pipeline
spec:
  rules:    
    - name: add-generate-policy
      match:
        resources:
          kinds:
            - Pipeline
      generate:
        synchronize: true
        kind: ClusterPolicy
        apiVersion: kyverno.io/v1
        name: "generate-{{request.object.metadata.name}}"
        data:
          spec:
            rules:
              - name: add-pipeline
                match:
                  resources:
                    kinds:
                      - Namespace
                    name: "{{request.object.metadata.name}}-run-*"
                generate:
                  kind: Pipeline
                  name: "{{request.object.metadata.name}}"
                  apiVersion: tekton.dev/v1beta1
                  namespace: "\\{{request.object.metadata.name}}"
                  synchronize: true
                  clone:
                    name: "{{request.object.metadata.name}}"
                    namespace: "{{request.object.metadata.namespace}}"
