apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:generate-additional-perms
  labels:
    app: kyverno
rules:
- apiGroups:
  - "*"
  resources:
  - secrets
  - serviceaccounts
  - persistentvolumeclaims
  - services
  - deployments
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - update
  - patch
  - delete
