---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-namespaces
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-pipeline
    match:
      resources:
        kinds:
        - PipelineRun
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    validate:
      message: "A namespace is required"
      pattern:
        metadata:
          namespace: "!default"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-label
spec:
  background: false
  rules:
  - name: add-annotation
    match:
      resources:
        kinds:
        - Namespace
    exclude:
      resources:
        namespaces:
        - common
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            kyverno.io/createdBy: "{{request.userInfo.username}}"
