---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-namespaces
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-pipeline
    match:
      resources:
        kinds:
        - Pipeline
    preconditions:
      all:
      - key: "{{ request.operation }}"
        operator: Equals
        value: CREATE
    validate:
      message: "A namespace is required"
      pattern:
        metadata:
          namespace: "!default"

