---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-bundle
  annotations:
    policies.kyverno.io/title: Require Bundle
    policies.kyverno.io/category: Tekton
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: TaskRun
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      PipelineRun and TaskRun resources must be executed from a bundle
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-pipeline-run
    match:
      resources:
        kinds:
        - PipelineRun
    validate:
      message: "a bundle is required"
      pattern:
        spec:
          pipelineRef:
            bundle: "?*"
  - name: check-task-run
    match:
      resources:
        kinds:
        - TaskRun
    validate:
      message: "a bundle is required"
      pattern:
        spec:
          taskRef:
            bundle: "?*"