apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
  namespace: pipelines
spec:
  tasks:
    - name: hello
      taskRef:
        name: hello
        kind: ClusterTask
    - name: goodbye
      runAfter:
        - hello
      taskRef:
        name: goodbye
        kind: ClusterTask

